### ISSUE TITLE
How to detect whether the picture is blurred or not blurred?

### ISSUE THREAD

**Issue by jamasBian** [bockp/Edge-Detection-project#3]
Can I use your project for this purpose? Is there a sample code?

**Comment by bockp** [comment]
Quite honestly, I'm not entirely sure.

This project was part of an attempt at replicating ImageJ's functionalities in javascript.

It was split up and assigned to different working groups within my Master's degree (this repo contains only the Edge Detection functions), and the combination of all those efforts is available here:

https://github.com/crazybiocomputing/times

The way to determine if an image is blurry is well described in the  answers of this StackOverflow question:

https://stackoverflow.com/questions/7765810/is-there-a-way-to-detect-if-an-image-is-blurry



I'm afraid I didn't go on to study in this domain (I do bioinformatics data analysis now), so that's as much help as I can provide on this subject.
Hopefully it'll help you with your problem.
